# Generated by Django 4.0.5 on 2022-06-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0004_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
    ]
